# Prevention Phase — Data Ingestion & Curation (Abid Extended Dataset)

## Objective

The purpose of this notebook is to curate the Extended Algerian Forest Fires Dataset before it is used for feature engineering and machine learning.

The goal is to ensure that the dataset is clean, consistent, and reproducible while preserving all relevant information.

---

## Input

Dataset:

- Extended Algerian Forest Fires Dataset
- Source: IEEE DataPort
- 1215 observations
- Nine Algerian regions
- Observation years: 2012, 2017, and 2021

Location:

```
data/Prevention/raw/abid_extended_forest_fires.xlsx
```

---

## Curation Steps

### 1. Initial inspection

The dataset structure was inspected by checking:

- dataset dimensions
- column names
- data types
- first and last rows

---

### 2. Date processing

The `DATE` column was converted to the datetime format.

Day, month, and year were extracted for temporal analysis.

---

### 3. Region standardization

The original column named `Bejaia 2021` was renamed to `Region`.

The embedded year was removed because it is already represented by the `DATE` column.

Examples:

| Original | Curated |
|-----------|---------|
| Bejaia 2021 | Bejaia |
| Tipaza2017 | Tipaza |
| Tizi-Ouzou2021 | Tizi-Ouzou |

---

### 4. Fire label standardization

The `Classes` column was normalized by:

- converting text to lowercase
- removing surrounding whitespace
- creating a binary label

Mapping:

- fire → 1
- not fire → 0

---

### 5. Data validation

The following validations were performed:

- missing values
- duplicate records
- invalid observation dates
- weather variable ranges
- fire class distribution

---

### 6. Exploratory Data Analysis

EDA included:

- descriptive statistics
- fire class balance
- fire occurrence by month
- regional distribution
- yearly distribution
- weather variable summary

---

## Data Quality Issues

During validation, six observations were found with inconsistent dates.

The years stored in the `DATE` column did not match the dataset description or the region metadata.

These records were flagged for review before creating the final curated dataset.

---

## Output

Curated dataset:

```
data/prevention/processed/abid_extended_clean.csv
```

This dataset is the input for the next stage:

- Feature Engineering
- Fire Prediction Modeling

---

## Reproducibility

The notebook is fully reproducible.

Running the notebook from top to bottom produces the same curated dataset from the raw data without modifying the original files.

In [30]:
from pathlib import Path
import pandas as pd

ROOT = Path("..")

df = pd.read_excel(
    ROOT / "data" / "Prevention" / "raw" / "abid_extended_forest_fires.xlsx"
)

df.head()

,DATE,Temperature,Ws,Rain,RH,FFMC,DMC,DC,ISI,BUI,FWI,Classes,Bejaia 2021
0,2021-06-01 00:00:00,27,13,2.1,59,63.6,5.2,8.3,1.0,5.0,0.4,not fire,Bejaia 2021
1,2021-06-02 00:00:00,24,10,0.3,72,55.1,4.1,7.7,0.5,4.0,0.2,not fire,Bejaia 2021
2,2021-06-03 00:00:00,27,11,3.0,76,47.1,3.0,8.3,0.2,3.2,0.1,not fire,Bejaia 2021
3,2021-06-04 00:00:00,28,9,1.0,70,52.3,3.1,8.4,0.3,3.2,0.1,not fire,Bejaia 2021
4,2021-06-05 00:00:00,28,11,0.1,64,73.4,4.5,16.9,1.6,5.4,0.7,not fire,Bejaia 2021

In [12]:
df.shape

(1215, 13)

In [13]:
df.columns

Index(['DATE', 'Temperature', '        Ws', '    Rain', 'RH', 'FFMC', 'DMC',
       'DC', 'ISI', 'BUI', 'FWI', 'Classes', 'Bejaia 2021'],
      dtype='str')

In [14]:
df.tail

<bound method NDFrame.tail of                      DATE  Temperature          Ws      Rain  RH  FFMC   DMC  \
0     2021-06-01 00:00:00           27          13       2.1  59  63.6   5.2
1     2021-06-02 00:00:00           24          10       0.3  72  55.1   4.1
2     2021-06-03 00:00:00           27          11       3.0  76  47.1   3.0
3     2021-06-04 00:00:00           28           9       1.0  70  52.3   3.1
4     2021-06-05 00:00:00           28          11       0.1  64  73.4   4.5
...                   ...          ...         ...       ...  ..   ...   ...
1210  2021-09-26 00:00:00           32          10       0.0  83  84.8  12.4
1211  2021-09-27 00:00:00           30          12       0.0  96  78.8  12.6
1212  2021-09-28 00:00:00           30          12       0.0  69  84.4  14.3
1213  2021-09-29 00:00:00           31          14       0.0  72  85.1  15.9
1214  2021-09-30 00:00:00           28          12       0.0  81  84.4  16.9

        DC  ISI   BUI  FWI   Classes     Bejaia 2021
0      8.3  1.0   5.0  0.4  not fire     Bejaia 2021
1      7.7  0.5   4.0  0.2  not fire     Bejaia 2021
2      8.3  0.2   3.2  0.1  not fire     Bejaia 2021
3      8.4  0.3   3.2  0.1  not fire     Bejaia 2021
4     16.9  1.6   5.4  0.7  not fire     Bejaia 2021
...    ...  ...   ...  ...       ...             ...
1210  34.5  3.4  13.1  4.2  not fire  Tizi-Ouzou2021
1211  41.6  1.8  14.4  2.1  not fire  Tizi-Ouzou2021
1212  48.7  3.5  16.5  5.1  not fire  Tizi-Ouzou2021
1213  56.0  4.3  18.6  6.7  not fire  Tizi-Ouzou2021
1214  62.8  3.5  20.2  5.8  not fire  Tizi-Ouzou2021

[1215 rows x 13 columns]>

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1215 entries, 0 to 1214
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   DATE         1215 non-null   object
 1   Temperature  1215 non-null   int64
 2           Ws   1215 non-null   int64
 3       Rain     1215 non-null   float64
 4   RH           1215 non-null   int64
 5   FFMC         1215 non-null   float64
 6   DMC          1215 non-null   float64
 7   DC           1215 non-null   float64
 8   ISI          1215 non-null   float64
 9   BUI          1215 non-null   float64
 10  FWI          1215 non-null   float64
 11  Classes      1215 non-null   str
 12  Bejaia 2021  1215 non-null   str
dtypes: float64(7), int64(3), object(1), str(2)
memory usage: 123.5+ KB

In [16]:
df.isnull().sum()

DATE           0
Temperature    0
        Ws     0
    Rain       0
RH             0
FFMC           0
DMC            0
DC             0
ISI            0
BUI            0
FWI            0
Classes        0
Bejaia 2021    0
dtype: int64

In [17]:
df.isna().sum()

DATE           0
Temperature    0
        Ws     0
    Rain       0
RH             0
FFMC           0
DMC            0
DC             0
ISI            0
BUI            0
FWI            0
Classes        0
Bejaia 2021    0
dtype: int64

In [18]:
df.duplicated().sum()

np.int64(0)

In [19]:
df.describe()

,Temperature,Ws,Rain,RH,FFMC,DMC,DC,ISI,BUI,FWI
count,1215.000000,1215.000000,1215.000000,1215.000000,1215.000000,1215.000000,1215.000000,1215.000000,1215.000000,1215.000000
mean,33.331687,16.598354,0.401893,52.925103,83.276379,26.275144,78.132181,9.904527,28.776049,15.497366
std,4.044168,5.744132,1.421008,19.883064,13.288328,22.505102,65.917867,11.244088,23.745075,15.967834
min,21.000000,5.000000,0.000000,11.000000,22.500000,0.200000,0.000000,0.000000,0.300000,0.000000
25%,31.000000,13.000000,0.000000,37.000000,79.800000,10.000000,25.400000,2.500000,10.850000,3.200000
50%,33.000000,15.000000,0.000000,53.000000,87.500000,18.600000,59.000000,6.700000,21.000000,11.100000
75%,36.000000,18.000000,0.100000,69.000000,91.900000,36.600000,111.800000,12.600000,40.600000,21.750000
max,43.000000,50.000000,20.200000,96.000000,98.600000,113.900000,308.200000,116.700000,113.800000,102.500000

# Clean the column names

In [34]:
print(df.columns.tolist())

df.columns = df.columns.str.strip()

print(df.columns.tolist())

['DATE', 'Temperature', 'Ws', 'Rain', 'RH', 'FFMC', 'DMC', 'DC', 'ISI', 'BUI', 'FWI', 'Classes', 'Bejaia 2021', 'fire_label']
['DATE', 'Temperature', 'Ws', 'Rain', 'RH', 'FFMC', 'DMC', 'DC', 'ISI', 'BUI', 'FWI', 'Classes', 'Bejaia 2021', 'fire_label']

In [35]:
df["DATE"] = pd.to_datetime(df["DATE"])
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1215 entries, 0 to 1214
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   DATE         1215 non-null   datetime64[ns]
 1   Temperature  1215 non-null   int64
 2   Ws           1215 non-null   int64
 3   Rain         1215 non-null   float64
 4   RH           1215 non-null   int64
 5   FFMC         1215 non-null   float64
 6   DMC          1215 non-null   float64
 7   DC           1215 non-null   float64
 8   ISI          1215 non-null   float64
 9   BUI          1215 non-null   float64
 10  FWI          1215 non-null   float64
 11  Classes      1215 non-null   str
 12  Bejaia 2021  1215 non-null   str
 13  fire_label   1215 non-null   int64
dtypes: datetime64[ns](1), float64(7), int64(4), str(2)
memory usage: 133.0 KB

# Inspect the target

In [36]:
df["Classes"].unique()

df["Classes"] = (
    df["Classes"]
      .astype(str)
      .str.strip()      # remove leading/trailing spaces
      .str.lower()      # lowercase everything
)

df["Classes"].unique()

df["fire_label"] = df["Classes"].map({
    "not fire": 0,
    "fire": 1
})

df[["Classes", "fire_label"]].head()

    Classes  fire_label
0  not fire           0
1  not fire           0
2  not fire           0
3  not fire           0
4  not fire           0

# Check class balance

In [39]:
df["fire_label"].value_counts()

fire_label
1    633
0    582
Name: count, dtype: int64

In [40]:
df["fire_label"].value_counts(normalize=True) * 100

fire_label
1    52.098765
0    47.901235
Name: proportion, dtype: float64

In [41]:
df["Bejaia 2021"].unique()

<StringArray>
[       'Bejaia 2021',         'Blida 2021',       'Bouira 2021 ',
     'Khenchela 2021',         'Tipaza2017',         'Setif 2021',
        'Tiaret 2021',        'Bejaia_2012', 'Sidi-Bel-Abass2012',
     'Tizi-Ouzou2021']
Length: 10, dtype: str

In [44]:
test = df.copy()

test["Bejaia 2021"] = test["Bejaia 2021"].str.strip()

test["Bejaia 2021"] = (
    test["Bejaia 2021"]
        .str.extract(r"(\d{4})")
        .astype(int)
)

test["date_year"] = test["DATE"].dt.year

In [45]:
(test["Bejaia 2021"] == test["date_year"]).value_counts()

True     1209
False       6
Name: count, dtype: int64

In [47]:
mismatches = test[test["Bejaia 2021"] != test["date_year"]]

mismatches[
    [
        "DATE",
        "Bejaia 2021",
        "Temperature",
        "RH",
        "Classes"
    ]
]

                             DATE  Bejaia 2021  Temperature  RH   Classes
721 2025-09-25 00:00:00.000000000         2021           35  38      fire
723 2025-09-27 00:00:00.000000000         2021           30  74  not fire
724 2025-09-28 00:00:00.000000000         2021           28  87  not fire
725 2025-09-29 00:00:00.000000000         2021           28  56  not fire
726 2025-09-30 00:00:00.000000000         2021           24  66  not fire
818 1970-01-01 00:00:00.000044439         2021           38  43      fire

In [50]:
df.loc[[721,723,724,725,726,818]]

,DATE,Temperature,Ws,Rain,RH,FFMC,DMC,DC,ISI,BUI,FWI,Classes,Bejaia 2021,fire_label
721,2025-09-25 00:00:00.000000000,35,35,0.0,38,92.8,14.5,29.9,37.3,14.4,31.3,fire,Setif 2021,1
723,2025-09-27 00:00:00.000000000,30,14,0.0,74,86.8,20.3,44.6,5.5,20.2,8.7,not fire,Setif 2021,0
724,2025-09-28 00:00:00.000000000,28,12,0.0,87,82.8,21.0,51.3,2.9,21.0,4.8,not fire,Setif 2021,0
725,2025-09-29 00:00:00.000000000,28,11,0.0,56,86.9,23.3,58.1,4.8,23.3,8.3,not fire,Setif 2021,0
726,2025-09-30 00:00:00.000000000,24,6,0.0,66,86.9,24.8,64.1,3.7,25.2,6.9,not fire,Setif 2021,0
818,1970-01-01 00:00:00.000044439,38,21,0.1,43,89.8,39.0,206.9,12.0,53.1,26.0,fire,Tiaret 2021,1

# Data validation:
 According to the dataset paper, observations exist only for
 2012, 2017 and 2021.

 Six records contained invalid years (2025 and 1970 date) in lines :
 721 / 723 / 724 / 725 / 726 / 818 
 After manual verification against the original Excel file,
 These records are dropped

In [51]:
type(df.loc[721, "DATE"])

pandas.Timestamp

In [52]:
df[df["DATE"].dt.year == 2025]

,DATE,Temperature,Ws,Rain,RH,FFMC,DMC,DC,ISI,BUI,FWI,Classes,Bejaia 2021,fire_label
721,2025-09-25,35,35,0.0,38,92.8,14.5,29.9,37.3,14.4,31.3,fire,Setif 2021,1
723,2025-09-27,30,14,0.0,74,86.8,20.3,44.6,5.5,20.2,8.7,not fire,Setif 2021,0
724,2025-09-28,28,12,0.0,87,82.8,21.0,51.3,2.9,21.0,4.8,not fire,Setif 2021,0
725,2025-09-29,28,11,0.0,56,86.9,23.3,58.1,4.8,23.3,8.3,not fire,Setif 2021,0
726,2025-09-30,24,6,0.0,66,86.9,24.8,64.1,3.7,25.2,6.9,not fire,Setif 2021,0

In [53]:
df[df["DATE"].dt.year == 1970]

,DATE,Temperature,Ws,Rain,RH,FFMC,DMC,DC,ISI,BUI,FWI,Classes,Bejaia 2021,fire_label
818,1970-01-01 00:00:00.000044439,38,21,0.1,43,89.8,39.0,206.9,12.0,53.1,26.0,fire,Tiaret 2021,1

In [55]:
valid_years = [2012, 2017, 2021]

invalid_dates = df[~df["DATE"].dt.year.isin(valid_years)]

print(invalid_dates)

df = df[df["DATE"].dt.year.isin(valid_years)]

                             DATE  Temperature  Ws  Rain  RH  FFMC   DMC  \
721 2025-09-25 00:00:00.000000000           35  35   0.0  38  92.8  14.5
723 2025-09-27 00:00:00.000000000           30  14   0.0  74  86.8  20.3
724 2025-09-28 00:00:00.000000000           28  12   0.0  87  82.8  21.0
725 2025-09-29 00:00:00.000000000           28  11   0.0  56  86.9  23.3
726 2025-09-30 00:00:00.000000000           24   6   0.0  66  86.9  24.8
818 1970-01-01 00:00:00.000044439           38  21   0.1  43  89.8  39.0

        DC   ISI   BUI   FWI   Classes  Bejaia 2021  fire_label
721   29.9  37.3  14.4  31.3      fire   Setif 2021           1
723   44.6   5.5  20.2   8.7  not fire   Setif 2021           0
724   51.3   2.9  21.0   4.8  not fire   Setif 2021           0
725   58.1   4.8  23.3   8.3  not fire   Setif 2021           0
726   64.1   3.7  25.2   6.9  not fire   Setif 2021           0
818  206.9  12.0  53.1  26.0      fire  Tiaret 2021           1

In [56]:
df = df.rename(columns={"Bejaia 2021": "Region"})

In [57]:
df["Region"] = (
    df["Region"]
      .astype(str)
      .str.strip()                    # Remove leading/trailing spaces
      .str.replace("_", " ", regex=False)
      .str.replace(r"\d{4}", "", regex=True)   # Remove 4-digit years
      .str.strip()
)

In [58]:
sorted(df["Region"].unique())

['Bejaia',
 'Blida',
 'Bouira',
 'Khenchela',
 'Setif',
 'Sidi-Bel-Abass',
 'Tiaret',
 'Tipaza',
 'Tizi-Ouzou']

In [59]:
df["Region"].value_counts()

Region
Bejaia            244
Blida             122
Bouira            122
Tipaza            122
Sidi-Bel-Abass    122
Tizi-Ouzou        122
Tiaret            121
Khenchela         117
Setif             117
Name: count, dtype: int64

In [62]:
weather_cols = ["Temperature", "RH", "Ws", "Rain", 
                "FFMC", "DMC", "DC", "ISI", "BUI", "FWI"]
print(df[weather_cols].describe().round(2))

       Temperature       RH       Ws     Rain     FFMC      DMC       DC  \
count      1209.00  1209.00  1209.00  1209.00  1209.00  1209.00  1209.00
mean         33.35    52.89    16.60     0.40    83.25    26.29    78.14
std           4.04    19.89     5.72     1.42    13.32    22.55    65.95
min          21.00    11.00     5.00     0.00    22.50     0.20     0.00
25%          31.00    37.00    13.00     0.00    79.70    10.00    25.30
50%          33.00    53.00    15.00     0.00    87.50    18.50    59.00
75%          36.00    69.00    18.00     0.10    91.90    36.60   111.80
max          43.00    96.00    50.00    20.20    98.60   113.90   308.20

           ISI      BUI      FWI
count  1209.00  1209.00  1209.00
mean      9.90    28.79    15.50
std      11.24    23.79    15.99
min       0.00     0.30     0.00
25%       2.40    10.70     3.20
50%       6.70    21.00    11.10
75%      12.60    40.70    21.70
max     116.70   113.80   102.50

In [63]:
df.groupby("Region")["fire_label"].value_counts()

Region          fire_label
Bejaia          0             138
                1             106
Blida           1              64
                0              58
Bouira          0              64
                1              58
Khenchela       1              75
                0              42
Setif           1              72
                0              45
Sidi-Bel-Abass  1              79
                0              43
Tiaret          1              86
                0              35
Tipaza          0              92
                1              30
Tizi-Ouzou      0              61
                1              61
Name: count, dtype: int64

# Saving the curated dataset into Processed

In [66]:
PROCESSED_DIR = ROOT / "data" / "Prevention" / "processed"
PROCESSED_DIR.mkdir(parents=True, exist_ok=True)
df.to_csv(PROCESSED_DIR / "abid_extended_clean.csv", index=False)
print(f"Saved: {df.shape[0]} rows × {df.shape[1]} columns")

Saved: 1209 rows × 14 columns